use std::collections::HashMap;
use std::fs;
use std::path::{ Path, PathBuf };

use regex::Regex;
use rusqlite::{ params, OptionalExtension };
use serde::{ Deserialize, Serialize };
use sha2::{ Digest, Sha256 };
use tauri::State;
use std::fmt::Write;
use crate::storage::DbState;
use crate::utils::error::{ AppError, Result };

use ts_rs::TS;

// ── Types ──────────────────────────────────────────────────────────────────

/// Options for a folder scan.
///
/// The TypeScript mirror of this struct is generated by `ts-rs` into
/// `src/app/lib/generated/` rather than written by hand. It was hand-written
/// once: when this struct gained `rename_all = "camelCase"` the mirror kept
/// saying `folder_path`, the two stayed internally consistent, every check
/// passed, and creating a project failed at run time. `ts-rs` reads the serde
/// attributes, so the two cannot disagree again.
#[derive(Serialize, Deserialize, Debug, Clone, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/app/lib/generated/")]
pub struct ScanOptions {
  pub folder_path: String,
  pub embed_images: bool,
  pub embed_threshold_kb: u32,
  pub input_regex: String,
  pub recursive: bool,
  pub folders_as_sequences: bool, // NEW: if true, subfolders become sequences
  /// Keep one frame out of this many from each video (1, or 0, keeps them
  /// all). A video is always one sequence, whatever `folders_as_sequences`.
  pub video_frame_step: u32,
}

#[derive(Serialize, Debug, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/app/lib/generated/")]
pub struct ScanResult {
  pub sequences_created: usize,
  pub frames_imported: usize,
  pub frames_embedded: usize,
  pub errors: Vec<String>,
}

/// Outcome of adding images to a project that already has some.
#[derive(Serialize, Debug, Default, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/app/lib/generated/")]
pub struct AddImagesResult {
  pub sequences_created: usize,
  pub frames_imported: usize,
  pub frames_embedded: usize,
  /// Files left out because the project already holds them.
  pub frames_skipped: usize,
  pub errors: Vec<String>,
}

#[derive(Debug)]
struct ImageFile {
  absolute_path: PathBuf,
  relative_path: String,
}

// ── Commands ───────────────────────────────────────────────────────────────

/// Scan a folder for images and import them into the database.
///
/// Behavior depends on `folders_as_sequences`:
/// - true: Subfolders become sequences with multiple frames, loose images become single-frame sequences
/// - false: Each image becomes its own single-frame sequence (flat mode)
#[tauri::command]
pub fn scan_and_import_folder(db: State<DbState>, options: ScanOptions) -> Result<ScanResult> {
  let folder_path = PathBuf::from(&options.folder_path);
  log::info!("[import] scanning {}", folder_path.display());
  if !folder_path.exists() {
    return Err(
      AppError::Io(
        std::io::Error::new(
          std::io::ErrorKind::NotFound,
          format!("Folder not found: {}", options.folder_path)
        )
      )
    );
  }

  let regex = Regex::new(&options.input_regex).map_err(|e|
    AppError::Generic(format!("Invalid regex: {}", e))
  )?;

  let (videos, image_files) =
    split_videos(scan_for_images(&folder_path, &folder_path, &regex, options.recursive)?);
  log::info!(
    "[import] {} image(s) and {} video(s) matched /{}/ (recursive: {}, foldersAsSequences: {})",
    image_files.len(),
    videos.len(),
    options.input_regex,
    options.recursive,
    options.folders_as_sequences
  );
  let sequences = group_into_sequences(image_files, options.folders_as_sequences);
  log::info!("[import] grouped into {} sequence(s)", sequences.len());
  let mut result = import_sequences(&db, sequences, options.embed_images, options.embed_threshold_kb)?;

  // Videos stay on disk whatever `embed_images` says: see `crate::video`.
  db.with_conn(|conn| {
    for video in &videos {
      match import_video(conn, video, options.video_frame_step) {
        Ok(frames) => {
          result.sequences_created += 1;
          result.frames_imported += frames;
        }
        Err(e) => result.errors.push(format!("Failed to import {}: {}", video.relative_path, e)),
      }
    }
    Ok(())
  })?;

  Ok(result)
}

/// Add the images of a folder to the open project, leaving out the ones it
/// already has.
///
/// Unlike [`scan_and_import_folder`], which fills an empty project, this has to
/// coexist with what is there, and where the folder sits decides how:
///
/// - **Inside the project's image folder** (or that folder itself): a rescan.
///   Paths stay relative to the image folder, so a file already imported is
///   recognised by its path and skipped, and new files of a known sequence
///   folder are appended to that sequence.
/// - **Anywhere else**: the images are embedded, whatever `embed_images` says.
///   A frame that is not embedded is read from `input_folder/relative_path`,
///   and a project has one `input_folder`, so a file outside it could never be
///   found again. Their paths are prefixed with the folder's own name to keep
///   them apart from the project's, and they always form new sequences.
///   A video cannot be embedded, so one found there is reported as an error.
#[tauri::command]
pub fn add_images_to_project(db: State<DbState>, options: ScanOptions) -> Result<AddImagesResult> {
  log::info!("[import] adding images from {}", options.folder_path);
  let regex = Regex::new(&options.input_regex).map_err(|e|
    AppError::Other(format!("Invalid filename pattern: {}", e))
  )?;
  db.with_conn(|conn| {
    crate::commands::users::require_admin(conn)?;
    let config = crate::storage::queries::get_project_config(conn)?;
    let input_folder = crate::commands::project::resolve_image_folder(&config)
      .map(|folder| folder.to_string_lossy().into_owned());
    add_images(conn, input_folder.as_deref(), &options, &regex)
  })
}

// ── Internal Functions ─────────────────────────────────────────────────────

fn add_images(
  conn: &rusqlite::Connection,
  input_folder: Option<&str>,
  options: &ScanOptions,
  regex: &Regex
) -> Result<AddImagesResult> {
  let folder = fs::canonicalize(&options.folder_path).map_err(|_|
    AppError::Other(format!("Folder not found: {}", options.folder_path))
  )?;
  // A project whose image folder has moved or is unplugged simply has no
  // "inside": everything is then embedded, which is always safe.
  let root = input_folder.and_then(|f| fs::canonicalize(f).ok());
  let inside = root.as_ref().is_some_and(|r| folder.starts_with(r));

  let (scan_root, prefix) = if inside {
    (root.unwrap(), None)
  } else {
    (folder.clone(), folder.file_name().map(PathBuf::from))
  };
  let embed_images = options.embed_images || !inside;

  let (videos, images) =
    split_videos(scan_for_images(&scan_root, &folder, regex, options.recursive)?);
  let mut groups: Vec<(String, Vec<ImageFile>)> =
    group_into_sequences(images, options.folders_as_sequences).into_iter().collect();
  groups.sort_by(|a, b| a.0.cmp(&b.0));

  // Every path the project already holds, with the hash of what is behind it.
  let mut known: HashMap<String, Option<String>> = {
    let mut stmt = conn.prepare(
      "SELECT relative_path, content_hash FROM frames WHERE relative_path IS NOT NULL"
    )?;
    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    rows.collect::<std::result::Result<_, _>>()?
  };

  let mut result = AddImagesResult::default();
  let tx = conn.unchecked_transaction()?;
  let mut next_sort_order: i64 = tx.query_row(
    "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM sequences",
    [],
    |row| row.get(0)
  )?;

  for (name, files) in groups {
    // Decide what is new before touching the sequences table, so a folder that
    // brings nothing does not leave an empty sequence behind.
    let mut fresh = Vec::new();
    for mut image in files {
      if let Some(prefix) = &prefix {
        image.relative_path = prefix.join(&image.relative_path).to_string_lossy().to_string();
      }
      match known.get(&image.relative_path) {
        None => fresh.push(image),
        // Same root, same path: the same file, already imported.
        Some(_) if inside => result.frames_skipped += 1,
        // Another root: only the content can tell a re-import from a namesake.
        Some(hash) => {
          let same = fs::read(&image.absolute_path).ok().map(|d| sha256_hex(&d)) == *hash;
          if same {
            result.frames_skipped += 1;
          } else {
            result.errors.push(format!(
              "{}: the project already has a different image under this path",
              image.relative_path
            ));
          }
        }
      }
    }
    if fresh.is_empty() {
      continue;
    }

    let existing: Option<i64> = tx
      .query_row("SELECT id FROM sequences WHERE name = ?1", params![name], |row| row.get(0))
      .optional()?;
    let (sequence_id, mut frame_index) = match existing {
      Some(id) if inside => {
        let next: i64 = tx.query_row(
          "SELECT COALESCE(MAX(frame_index), -1) + 1 FROM frames WHERE sequence_id = ?1",
          params![id],
          |row| row.get(0)
        )?;
        (id, next as usize)
      }
      taken => {
        let name = if taken.is_some() { free_sequence_name(&tx, &name)? } else { name };
        tx.execute(
          "INSERT INTO sequences (name, sort_order) VALUES (?1, ?2)",
          params![name, next_sort_order]
        )?;
        next_sort_order += 1;
        (tx.last_insert_rowid(), 0)
      }
    };
    let imported_before = result.frames_imported;

    for image in &fresh {
      match import_frame(&tx, sequence_id, frame_index, image, embed_images, options.embed_threshold_kb) {
        Ok(embedded) => {
          frame_index += 1;
          result.frames_imported += 1;
          if embedded {
            result.frames_embedded += 1;
          }
          known.insert(image.relative_path.clone(), None);
        }
        Err(e) => {
          result.errors.push(format!("Failed to import {}: {}", image.relative_path, e));
        }
      }
    }

    if existing.is_none() || !inside {
      if result.frames_imported > imported_before {
        result.sequences_created += 1;
      } else {
        // Every file failed to decode: do not leave an empty sequence behind.
        tx.execute("DELETE FROM sequences WHERE id = ?1", params![sequence_id])?;
      }
    }
  }

  for video in &videos {
    if !inside {
      result.errors.push(format!(
        "{}: a video is read from the project's image folder and cannot be copied into \
         the project file. Move it into that folder first.",
        video.relative_path
      ));
      continue;
    }
    let known: bool = tx.query_row(
      "SELECT EXISTS (SELECT 1 FROM frames f JOIN videos v ON v.id = f.video_id
                      WHERE v.relative_path = ?1)",
      params![video.relative_path],
      |row| row.get(0)
    )?;
    if known {
      result.frames_skipped += 1;
      continue;
    }
    match import_video(&tx, video, options.video_frame_step) {
      Ok(frames) => {
        result.sequences_created += 1;
        result.frames_imported += frames;
      }
      Err(e) => result.errors.push(format!("Failed to import {}: {}", video.relative_path, e)),
    }
  }

  tx.commit()?;
  log::info!(
    "[import] added {} frame(s), skipped {}, {} error(s)",
    result.frames_imported,
    result.frames_skipped,
    result.errors.len()
  );
  Ok(result)
}

/// `name (2)`, `name (3)`, … — the first one no sequence uses yet.
fn free_sequence_name(conn: &rusqlite::Connection, name: &str) -> Result<String> {
  for n in 2.. {
    let candidate = format!("{} ({})", name, n);
    let taken: bool = conn.query_row(
      "SELECT EXISTS (SELECT 1 FROM sequences WHERE name = ?1)",
      params![candidate],
      |row| row.get(0)
    )?;
    if !taken {
      return Ok(candidate);
    }
  }
  unreachable!()
}

fn sha256_hex(data: &[u8]) -> String {
  let mut hasher = Sha256::new();
  hasher.update(data);
  let digest = hasher.finalize();
  let mut hex = String::with_capacity(digest.len() * 2);
  for byte in digest {
    write!(&mut hex, "{:02x}", byte).unwrap();
  }
  hex
}

/// Recursively scan folder for image files matching the regex
fn scan_for_images(
  root: &Path,
  current: &Path,
  regex: &Regex,
  recursive: bool
) -> Result<Vec<ImageFile>> {
  let mut images = Vec::new();

  let entries = fs::read_dir(current).map_err(|e| AppError::Io(e))?;

  for entry in entries {
    let entry = entry.map_err(|e| AppError::Io(e))?;
    let path = entry.path();
    let file_type = entry.file_type().map_err(|e| AppError::Io(e))?;

    if file_type.is_dir() {
      if recursive {
        let sub_images = scan_for_images(root, &path, regex, recursive)?;
        images.extend(sub_images);
      }
    } else if file_type.is_file() {
      let file_name = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");

      if regex.is_match(file_name) {
        let relative_path = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().to_string();

        images.push(ImageFile {
          absolute_path: path,
          relative_path,
        });
      }
    }
  }

  // Sort by path for consistent ordering
  images.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));

  Ok(images)
}

/// Separate the videos (first) from the images among scanned files.
fn split_videos(files: Vec<ImageFile>) -> (Vec<ImageFile>, Vec<ImageFile>) {
  files.into_iter().partition(|f| crate::video::is_video(&f.absolute_path))
}

/// Group images into sequences
///
/// If `folders_as_sequences` is true:
///   - Images in subfolders: grouped by subfolder name
///   - Images in root: each becomes its own sequence
///
/// If `folders_as_sequences` is false:
///   - Each image becomes its own single-frame sequence (flat mode)
fn group_into_sequences(
  images: Vec<ImageFile>,
  folders_as_sequences: bool
) -> HashMap<String, Vec<ImageFile>> {
  let mut sequences: HashMap<String, Vec<ImageFile>> = HashMap::new();
  for image in images {
    let sequence_name = if folders_as_sequences {
      get_sequence_name_from_path(&image.relative_path)
    } else {
      // Flat mode: use full relative path as unique key
      image.relative_path.clone()
    };
    sequences.entry(sequence_name).or_default().push(image);
  }
  for frames in sequences.values_mut() {
    frames.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
  }
  sequences
}

/// Extract sequence name from image path (filename without extension)
fn get_sequence_name_from_path(relative_path: &str) -> String {
  Path::new(relative_path)
    .parent()
    .filter(|p| !p.as_os_str().is_empty())
    .map(|p| p.to_string_lossy().to_string())
    .unwrap_or_else(|| {
      // No parent directory (root-level image), use filename stem
      Path::new(relative_path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unnamed")
        .to_string()
    })
}
/// Import sequences and frames into database
fn import_sequences(
  db: &State<DbState>,
  sequences: HashMap<String, Vec<ImageFile>>,
  embed_images: bool,
  embed_threshold_kb: u32
) -> Result<ScanResult> {
  let mut result = ScanResult {
    sequences_created: 0,
    frames_imported: 0,
    frames_embedded: 0,
    errors: Vec::new(),
  };

  db.with_conn(|conn| {
    // Sort sequences by name for consistent ordering
    let mut sequence_names: Vec<_> = sequences.keys().collect();
    sequence_names.sort();

    for (sort_order, sequence_name) in sequence_names.iter().enumerate() {
      let frames = sequences.get(*sequence_name).unwrap();

      conn.execute(
        "INSERT INTO sequences (name, sort_order) VALUES (?1, ?2)",
        params![sequence_name, sort_order as i32]
      )?;
      let sequence_id = conn.last_insert_rowid();
      result.sequences_created += 1;

      for (frame_index, image) in frames.iter().enumerate() {
        match import_frame(conn, sequence_id, frame_index, image, embed_images, embed_threshold_kb) {
          Ok(embedded) => {
            result.frames_imported += 1;
            if embedded {
              result.frames_embedded += 1;
            }
          }
          Err(e) => {
            result.errors.push(format!("Failed to import {}: {}", image.relative_path, e));
          }
        }
      }
    }

    Ok(result)
  })
}

/// Import a single frame into database
fn import_frame(
  conn: &rusqlite::Connection,
  sequence_id: i64,
  frame_index: usize,
  image: &ImageFile,
  embed_images: bool,
  embed_threshold_kb: u32
) -> Result<bool> {
  let file_data = fs::read(&image.absolute_path).map_err(|e| AppError::Io(e))?;

  let content_hash = sha256_hex(&file_data);

  let (width, height) = get_image_dimensions(&file_data)?;

  let file_size_kb = (file_data.len() as u32) / 1024;
  let should_embed = embed_images || file_size_kb < embed_threshold_kb;

  let embedded_data: Option<Vec<u8>> = if should_embed { Some(file_data) } else { None };

  // Store relative path only if not embedded
  let relative_path: Option<&str> = Some(&image.relative_path);

  conn.execute(
    "INSERT INTO frames (
            sequence_id, frame_index, relative_path, content_hash,
            embedded_data, width, height, reviewed
        ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 0)",
    params![
      sequence_id,
      frame_index as i32,
      relative_path,
      content_hash,
      embedded_data,
      width,
      height
    ]
  )?;

  Ok(should_embed)
}

/// Import a video as a new sequence, one frame out of `step`. Returns how many
/// frames it gave.
///
/// Indexing the file is the slow part and happens first, so nothing is written
/// for a video ffmpeg cannot read.
fn import_video(conn: &rusqlite::Connection, video: &ImageFile, step: u32) -> Result<usize> {
  let index = crate::video::probe(&video.absolute_path)?;
  log::info!(
    "[import] {}: {} frame(s), {}x{}, {:.3} fps",
    video.relative_path,
    index.times.len(),
    index.width,
    index.height,
    index.fps
  );

  // A savepoint rather than a transaction: this runs both on its own and
  // inside the transaction of `add_images`.
  conn.execute_batch("SAVEPOINT import_video")?;
  let inserted = insert_video(conn, &video.relative_path, &index, step);
  conn.execute_batch(if inserted.is_ok() {
    "RELEASE import_video"
  } else {
    "ROLLBACK TO import_video; RELEASE import_video"
  })?;
  inserted
}

/// Write the sequence, video and frame rows of an indexed video.
fn insert_video(
  conn: &rusqlite::Connection,
  relative_path: &str,
  index: &crate::video::VideoIndex,
  step: u32
) -> Result<usize> {
  // Named after the file, folders included: two videos of one folder are two
  // sequences, unlike two images.
  let name = Path::new(relative_path).with_extension("").to_string_lossy().to_string();
  let taken: bool = conn.query_row(
    "SELECT EXISTS (SELECT 1 FROM sequences WHERE name = ?1)",
    params![name],
    |row| row.get(0)
  )?;
  let name = if taken { free_sequence_name(conn, &name)? } else { name };
  conn.execute(
    "INSERT INTO sequences (name, sort_order)
     VALUES (?1, (SELECT COALESCE(MAX(sort_order), -1) + 1 FROM sequences))",
    params![name]
  )?;
  let sequence_id = conn.last_insert_rowid();

  // Deleting a sequence deletes its frames, not the video they came from. A
  // video left without frames is as good as absent, and is replaced here.
  conn.execute(
    "DELETE FROM videos WHERE relative_path = ?1
       AND NOT EXISTS (SELECT 1 FROM frames WHERE video_id = videos.id)",
    params![relative_path]
  )?;
  conn.execute(
    "INSERT INTO videos (relative_path, frame_count, fps, seek_margin, seek_preroll)
     VALUES (?1, ?2, ?3, ?4, ?5)",
    params![relative_path, index.times.len() as i64, index.fps, index.seek_margin, index.seek_preroll]
  )?;
  let video_id = conn.last_insert_rowid();

  let mut stmt = conn.prepare(
    "INSERT INTO frames (
            sequence_id, frame_index, relative_path, width, height, reviewed,
            video_id, video_frame, video_time
        ) VALUES (?1, ?2, ?3, ?4, ?5, 0, ?6, ?7, ?8)"
  )?;
  let mut frames = 0;
  for (video_frame, time) in index.times.iter().enumerate().step_by(step.max(1) as usize) {
    // Exports and annotation imports identify a frame by this path, so each
    // frame needs one of its own. The extension is a lossless format's: what
    // a frame of a video would be saved as.
    let frame_path = Path::new(relative_path).join(format!("{:06}.png", video_frame));
    stmt.execute(params![
      sequence_id,
      frames as i64,
      frame_path.to_string_lossy(),
      index.width,
      index.height,
      video_id,
      video_frame as i64,
      time
    ])?;
    frames += 1;
  }
  Ok(frames)
}

/// Get image dimensions from raw bytes
fn get_image_dimensions(data: &[u8]) -> Result<(i32, i32)> {
  let img = image
    ::load_from_memory(data)
    .map_err(|e| AppError::Generic(format!("Failed to decode image: {}", e)))?;

  Ok((img.width() as i32, img.height() as i32))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A throwaway directory holding `names`, removed when the test ends.
    fn dir_with(label: &str, names: &[&str]) -> PathBuf {
        // Labelled per test: naming these by file count made two tests share a
        // directory and clobber each other under the parallel test runner.
        let root = std::env::temp_dir().join(format!("dida-scan-{}-{}", std::process::id(), label));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        for n in names {
            let p = root.join(n);
            if let Some(parent) = p.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(&p, b"x").unwrap();
        }
        root
    }

    /// Exactly the pattern DEFAULT_PROJECT_CONFIG ships on the TypeScript side.
    const DEFAULT_REGEX: &str = r"\.(png|jpe?g|bmp|tiff?)$";

    #[test]
    fn the_default_pattern_matches_a_flat_folder_of_pngs() {
        let root = dir_with("flat_pngs", &["a.png", "b.png", "c.png"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        let found = scan_for_images(&root, &root, &re, true).unwrap();
        assert_eq!(found.len(), 3, "found: {:?}", found.iter().map(|i| &i.relative_path).collect::<Vec<_>>());
    }

    #[test]
    fn the_default_pattern_ignores_non_images() {
        let root = dir_with("non_images", &["a.png", "notes.txt", "data.csv"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        assert_eq!(scan_for_images(&root, &root, &re, true).unwrap().len(), 1);
    }

    #[test]
    fn the_default_pattern_is_case_sensitive() {
        // Worth pinning: a folder of .PNG files silently imports nothing, which
        // looks identical to "the scan is broken".
        let root = dir_with("case", &["a.PNG", "b.JPG"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        assert_eq!(scan_for_images(&root, &root, &re, true).unwrap().len(), 0);
    }

    #[test]
    fn flat_mode_gives_each_image_its_own_sequence() {
        let root = dir_with("flat_mode", &["a.png", "b.png"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        let found = scan_for_images(&root, &root, &re, true).unwrap();
        assert_eq!(group_into_sequences(found, false).len(), 2);
    }

    #[test]
    fn folder_mode_groups_by_subfolder() {
        let root = dir_with("folder_mode", &["s1/a.png", "s1/b.png", "s2/c.png"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        let found = scan_for_images(&root, &root, &re, true).unwrap();
        let seqs = group_into_sequences(found, true);
        assert_eq!(seqs.len(), 2);
        assert_eq!(seqs.values().map(|v| v.len()).sum::<usize>(), 3);
    }

    // ---- adding to an existing project ----

    /// A 1x1 PNG whose single pixel is `shade`, so two files can differ.
    fn png(shade: u8) -> Vec<u8> {
        let mut bytes = Vec::new();
        image::DynamicImage::ImageLuma8(image::GrayImage::from_pixel(1, 1, image::Luma([shade])))
            .write_to(&mut std::io::Cursor::new(&mut bytes), image::ImageFormat::Png)
            .unwrap();
        bytes
    }

    fn write_png(root: &Path, name: &str, shade: u8) {
        let p = root.join(name);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(p, png(shade)).unwrap();
    }

    fn options(folder: &Path, folders_as_sequences: bool) -> ScanOptions {
        ScanOptions {
            folder_path: folder.to_string_lossy().to_string(),
            embed_images: false,
            embed_threshold_kb: 0,
            input_regex: DEFAULT_REGEX.into(),
            recursive: true,
            folders_as_sequences,
            video_frame_step: 1,
        }
    }

    fn open_project() -> rusqlite::Connection {
        crate::storage::queries::create_database(Path::new(":memory:")).unwrap()
    }

    fn add(conn: &rusqlite::Connection, root: &Path, folder: &Path, as_sequences: bool) -> AddImagesResult {
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        add_images(conn, Some(&root.to_string_lossy()), &options(folder, as_sequences), &re).unwrap()
    }

    fn column<T: rusqlite::types::FromSql>(conn: &rusqlite::Connection, sql: &str) -> Vec<T> {
        let mut stmt = conn.prepare(sql).unwrap();
        let rows = stmt.query_map([], |r| r.get(0)).unwrap();
        rows.map(|r| r.unwrap()).collect()
    }

    #[test]
    fn rescanning_the_image_folder_adds_only_what_is_new() {
        let root = dir_with("add_rescan", &[]);
        write_png(&root, "s1/a.png", 1);
        let conn = open_project();
        let first = add(&conn, &root, &root, true);
        assert_eq!((first.sequences_created, first.frames_imported, first.frames_skipped), (1, 1, 0));

        write_png(&root, "s1/b.png", 2);
        write_png(&root, "s2/c.png", 3);
        let second = add(&conn, &root, &root, true);
        assert_eq!((second.sequences_created, second.frames_imported, second.frames_skipped), (1, 2, 1));
        assert_eq!(second.frames_embedded, 0, "inside the image folder, files stay on disk");

        // b.png joined the sequence a.png was already in, after it.
        let s1: Vec<String> = column(
            &conn,
            "SELECT relative_path FROM frames f JOIN sequences s ON s.id = f.sequence_id
             WHERE s.name = 's1' ORDER BY frame_index",
        );
        assert_eq!(s1.len(), 2);
        assert!(s1[0].ends_with("a.png") && s1[1].ends_with("b.png"), "{s1:?}");

        let third = add(&conn, &root, &root, true);
        assert_eq!((third.sequences_created, third.frames_imported, third.frames_skipped), (0, 0, 3));
    }

    #[test]
    fn a_subfolder_of_the_image_folder_keeps_paths_relative_to_the_root() {
        let root = dir_with("add_subfolder", &[]);
        write_png(&root, "s1/a.png", 1);
        let conn = open_project();
        add(&conn, &root, &root.join("s1"), true);
        let paths: Vec<String> = column(&conn, "SELECT relative_path FROM frames");
        assert_eq!(paths, [Path::new("s1").join("a.png").to_string_lossy().to_string()]);
    }

    #[test]
    fn a_folder_outside_the_image_folder_is_embedded_under_its_own_name() {
        let root = dir_with("add_outside_root", &[]);
        write_png(&root, "a.png", 1);
        let other = dir_with("add_outside_other", &[]);
        write_png(&other, "a.png", 2);

        let conn = open_project();
        add(&conn, &root, &root, false);
        let added = add(&conn, &root, &other, false);
        assert_eq!((added.frames_imported, added.frames_embedded, added.frames_skipped), (1, 1, 0));

        let embedded: Vec<bool> = column(
            &conn,
            "SELECT embedded_data IS NOT NULL FROM frames ORDER BY id",
        );
        assert_eq!(embedded, [false, true]);
        let paths: Vec<String> = column(&conn, "SELECT relative_path FROM frames ORDER BY id");
        assert_ne!(paths[0], paths[1], "the namesake must not shadow the project's own a.png");

        // Importing the same outside folder again brings nothing new.
        let again = add(&conn, &root, &other, false);
        assert_eq!((again.frames_imported, again.frames_skipped), (0, 1));
    }

    #[test]
    fn an_outside_sequence_never_merges_into_one_of_the_same_name() {
        let root = dir_with("add_names_root", &[]);
        write_png(&root, "s1/a.png", 1);
        let other = dir_with("add_names_other", &[]);
        write_png(&other, "s1/z.png", 2);

        let conn = open_project();
        add(&conn, &root, &root, true);
        add(&conn, &root, &other, true);
        let names: Vec<String> = column(&conn, "SELECT name FROM sequences ORDER BY sort_order");
        assert_eq!(names, ["s1", "s1 (2)"]);
    }

    #[test]
    fn a_file_that_cannot_be_decoded_is_reported_and_leaves_no_empty_sequence() {
        let root = dir_with("add_broken", &["broken.png"]);
        let conn = open_project();
        let result = add(&conn, &root, &root, false);
        assert_eq!(result.frames_imported, 0);
        assert_eq!(result.errors.len(), 1);
        assert_eq!(column::<String>(&conn, "SELECT name FROM sequences").len(), 0);
    }

    #[test]
    fn non_recursive_ignores_subfolders() {
        let root = dir_with("non_recursive", &["top.png", "sub/deep.png"]);
        let re = Regex::new(DEFAULT_REGEX).unwrap();
        assert_eq!(scan_for_images(&root, &root, &re, false).unwrap().len(), 1);
    }

    // ---- videos ----

    fn video_index(frames: usize) -> crate::video::VideoIndex {
        crate::video::VideoIndex {
            times: (0..frames).map(|n| n as f64 / 30.0).collect(),
            seek_margin: 1.0 / 120.0,
            seek_preroll: 0.1,
            fps: 30.0,
            width: 4,
            height: 2,
        }
    }

    #[test]
    fn a_video_becomes_one_sequence_of_its_frames() {
        let conn = open_project();
        let clip = Path::new("day1").join("clip.mp4").to_string_lossy().to_string();
        assert_eq!(insert_video(&conn, &clip, &video_index(5), 1).unwrap(), 5);

        let names: Vec<String> = column(&conn, "SELECT name FROM sequences");
        assert_eq!(names, [Path::new("day1").join("clip").to_string_lossy().to_string()]);
        let source: Vec<i64> = column(&conn, "SELECT video_frame FROM frames ORDER BY frame_index");
        assert_eq!(source, [0, 1, 2, 3, 4]);
        let paths: Vec<String> = column(&conn, "SELECT DISTINCT relative_path FROM frames");
        assert_eq!(paths.len(), 5, "every frame has a path of its own");
        assert_eq!(column::<i64>(&conn, "SELECT frame_count FROM videos"), [5]);
    }

    #[test]
    fn a_frame_step_keeps_one_frame_out_of_n() {
        let conn = open_project();
        assert_eq!(insert_video(&conn, "clip.mp4", &video_index(10), 4).unwrap(), 3);
        let source: Vec<i64> = column(&conn, "SELECT video_frame FROM frames ORDER BY frame_index");
        assert_eq!(source, [0, 4, 8]);
        let index: Vec<i64> = column(&conn, "SELECT frame_index FROM frames ORDER BY frame_index");
        assert_eq!(index, [0, 1, 2], "frames stay contiguous in their sequence");
        let times: Vec<f64> = column(&conn, "SELECT video_time FROM frames ORDER BY frame_index");
        assert!((times[1] - 4.0 / 30.0).abs() < 1e-12);
        // A step of 0 is "no step", not a division by zero.
        assert_eq!(insert_video(&conn, "other.mp4", &video_index(3), 0).unwrap(), 3);
    }

    #[test]
    fn a_video_named_like_an_existing_sequence_gets_its_own() {
        let root = dir_with("video_names", &[]);
        write_png(&root, "clip/a.png", 1);
        let conn = open_project();
        add(&conn, &root, &root, true);
        insert_video(&conn, "clip.mp4", &video_index(2), 1).unwrap();
        let names: Vec<String> = column(&conn, "SELECT name FROM sequences ORDER BY sort_order");
        assert_eq!(names, ["clip", "clip (2)"]);
    }

    #[test]
    fn deleting_a_sequence_leaves_its_video_importable_again() {
        let conn = open_project();
        insert_video(&conn, "clip.mp4", &video_index(2), 1).unwrap();
        // The same file twice is refused by the schema, whatever the caller checks.
        assert!(insert_video(&conn, "clip.mp4", &video_index(2), 1).is_err());

        conn.execute("DELETE FROM sequences", []).unwrap();
        assert_eq!(insert_video(&conn, "clip.mp4", &video_index(3), 1).unwrap(), 3);
        assert_eq!(column::<i64>(&conn, "SELECT frame_count FROM videos"), [3]);
    }

    const VIDEO_REGEX: &str = r"\.(png|mp4)$";

    /// Run the ffmpeg the application would, or `None` where there is none
    /// (the tests needing it are then skipped).
    fn ffmpeg(args: &[&str]) -> Option<Vec<u8>> {
        let exe = std::env::var("DIDASCALIE_FFMPEG").unwrap_or_else(|_| "ffmpeg".into());
        let out = std::process::Command::new(exe).args(["-v", "error"]).args(args).output().ok()?;
        assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
        Some(out.stdout)
    }

    /// The property everything rests on: frame `n` of a project decodes to
    /// frame `n` of the video, however it is asked for — alone and out of
    /// order, or in order with the following frames decoded along (every
    /// frame of the video, then one out of three). B-frames and a short GOP
    /// make most frames neither keyframes nor in file order.
    #[test]
    fn a_video_frame_decodes_to_the_same_pixels_as_playing_the_video() {
        use crate::commands::frame::{read_frame_bytes, read_frame_bytes_ahead};

        let root = dir_with("video_exact", &[]);
        let clip_arg = root.join("alone.mp4").to_string_lossy().to_string();
        let (w, h, count) = (64usize, 48usize, 80usize);
        if ffmpeg(&[
            "-f", "lavfi", "-i", "testsrc=size=64x48:rate=30", "-frames:v", "80",
            "-c:v", "mpeg4", "-bf", "2", "-g", "12", "-q:v", "3", "-y", &clip_arg,
        ]).is_none() {
            eprintln!("ffmpeg not found: skipping");
            return;
        }
        let played = ffmpeg(&[
            "-i", &clip_arg, "-map", "0:v:0", "-sws_flags", "bitexact",
            "-pix_fmt", "rgb24", "-f", "rawvideo", "-",
        ]).unwrap();
        assert_eq!(played.len(), w * h * 3 * count);
        // Decoded frames are cached by file: a file per way of reading, or the
        // second way would only read what the first decoded.
        fs::copy(root.join("alone.mp4"), root.join("run.mp4")).unwrap();
        fs::copy(root.join("alone.mp4"), root.join("sparse.mp4")).unwrap();

        type Read = fn(&DbState, i64) -> Result<(crate::commands::frame::FrameMeta, Vec<u8>)>;
        let cases: [(&str, u32, bool, Read); 3] = [
            ("alone", 1, true, read_frame_bytes),
            ("run", 1, false, read_frame_bytes_ahead),
            ("sparse", 3, false, read_frame_bytes_ahead),
        ];
        for (name, step, backwards, read) in cases {
            let conn = open_project();
            conn.execute(
                "INSERT OR REPLACE INTO project (id, config) VALUES (1, json_object('input_folder', ?1))",
                params![root.to_string_lossy()],
            ).unwrap();
            let re = Regex::new(&format!(r"^{}\.mp4$", name)).unwrap();
            let mut opts = options(&root, false);
            opts.video_frame_step = step;
            let result = add_images(&conn, Some(&root.to_string_lossy()), &opts, &re).unwrap();
            assert_eq!(result.errors, Vec::<String>::new());
            let expected = count.div_ceil(step as usize);
            assert_eq!((result.sequences_created, result.frames_imported), (1, expected), "{name}");

            // A rescan finds the video already there.
            let again = add_images(&conn, Some(&root.to_string_lossy()), &opts, &re).unwrap();
            assert_eq!((again.frames_imported, again.frames_skipped), (0, 1));

            let mut frames: Vec<(i64, i64)> = {
                let mut stmt =
                    conn.prepare("SELECT id, video_frame FROM frames ORDER BY frame_index").unwrap();
                let rows = stmt.query_map([], |r| Ok((r.get(0)?, r.get(1)?))).unwrap();
                rows.map(|r| r.unwrap()).collect()
            };
            if backwards {
                frames.reverse();
            }

            let db = DbState::new();
            db.set(conn);
            for (frame_id, video_frame) in frames {
                let (meta, bytes) = read(&db, frame_id).unwrap();
                assert_eq!((meta.frame.width, meta.frame.height), (w as i32, h as i32));
                let decoded = image::load_from_memory(&bytes).unwrap().to_rgb8();
                let n = video_frame as usize;
                assert!(
                    decoded.as_raw()[..] == played[n * w * h * 3..(n + 1) * w * h * 3],
                    "{name}: frame {n} of the video"
                );
            }
        }
    }

    #[test]
    fn a_video_outside_the_image_folder_is_refused() {
        let root = dir_with("video_outside_root", &[]);
        let other = dir_with("video_outside_other", &["clip.mp4"]);
        let conn = open_project();
        let re = Regex::new(VIDEO_REGEX).unwrap();
        let result =
            add_images(&conn, Some(&root.to_string_lossy()), &options(&other, false), &re).unwrap();
        assert_eq!(result.frames_imported, 0);
        assert_eq!(result.errors.len(), 1);
        assert_eq!(column::<String>(&conn, "SELECT name FROM sequences").len(), 0);
    }
}
