pub mod flood_fill;
pub mod superpixel;
pub mod images;
pub mod io;
pub mod segmentation;
pub mod annotation;
pub mod project;
pub mod users;
pub mod agreement;
#[cfg(not(target_os = "android"))]
pub mod project_edit;
pub mod classification;
pub mod text_description;
pub mod frame;
pub mod inspect;
pub mod sequences;
pub mod formats;
pub mod dataset_io;
pub mod registration;
/// The bridge to the user's own Python functions (`didascalie.com`).
#[cfg(not(target_os = "android"))]
pub mod python;
pub mod skeletonize;
pub mod propagation;
/// Scribble-conditioned segmentation head. Depends on `ort` and `burn`.
#[cfg(not(target_os = "android"))]
pub mod ml;
#[cfg(target_os = "android")]
#[path = "ml_stub.rs"]
pub mod ml;
pub mod vector;
pub mod vectorize;
pub mod volume;
pub mod window;
#[cfg(not(target_os = "android"))]
pub mod dl;
pub mod device_files;
